language: objective-c
before_install:
  - gem install cocoapods
  - gem install xcpretty
script:
  - set -o pipefail && xcodebuild -project Stencil.xcodeproj -scheme Stencil-OSX test | xcpretty -c
  - set -o pipefail && xcodebuild -project Stencil.xcodeproj -scheme Stencil-iOS test | xcpretty -c

