language: objective-c
before_install:
- gem install cocoapods --pre
- gem install xcpretty
script:
- set -o pipefail
- xcodebuild -project Stencil.xcodeproj -scheme Stencil test | xcpretty -c
- xcodebuild -project Stencil.xcodeproj -scheme Stencil test -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
- pod lib lint --quick
